'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const C=require('../src/frameflow-core'),{Engine}=require('../src/frameflow-engine');
const engine=new Engine(path.join(__dirname,'..','runtime',process.platform)),checks=[];
const check=(name,test)=>{assert.ok(test,name);checks.push(name);console.log('PASS '+name);};
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
async function wait(){const until=Date.now()+180000;while(engine.status()?.state==='running'){if(Date.now()>until){engine.cancel();throw Error('Export timeout');}await new Promise(r=>setTimeout(r,80));}return engine.status();}
async function main(){
 fs.mkdirSync(path.join(__dirname,'..','.build-cache'),{recursive:true});
 check('新项目默认45分钟',C.initial().settings.minutes===45);
 const old=C.initial();old.settings.minutes=30;delete old.settings.concat;check('旧项目保留已保存时长并兼容默认拼接',C.parse(old).settings.minutes===30&&C.parse(old).settings.concat);
 const settings=C.initial();settings.settings.concat=false;settings.settings.fit='none';const savedSettings=C.parse(JSON.stringify(settings));check('开关状态保存恢复',savedSettings.settings.concat===false&&savedSettings.settings.fit==='none');
 check('输出用时按累计分钟格式化',C.elapsed(3661.9)==='61分01秒'&&C.elapsed(0)==='00分00秒');
 const dir=await fs.promises.mkdtemp(path.join(__dirname,'..','.build-cache','acceptance-'));console.log('ARTIFACTS '+dir);const out=path.join(dir,'输出 中文'),source=path.join(dir,"横屏 O'Brien.mp4"),portrait=path.join(dir,'无音轨竖屏.mp4');await fs.promises.mkdir(out);
 const health=await engine.health();check('引擎及元数据工具可运行',health.ready);
 await engine.run('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=320x180:rate=25:duration=4','-f','lavfi','-i','sine=frequency=440:duration=4','-c:v','libx264','-preset','ultrafast','-crf','18','-pix_fmt','yuv420p','-g','25','-bf','0','-c:a','aac','-shortest',source]);
 await engine.run('ffmpeg',['-v','error','-f','lavfi','-i','color=c=white:size=180x320:rate=30:duration=3','-c:v','libx264','-pix_fmt','yuv420p',portrait]);
 const p=C.initial();p.settings={...p.settings,minutes:0,seconds:3,output:out,baseName:'验收课程'};p.files=[source,portrait].map(file=>({id:C.id(),path:file,name:path.basename(file),selected:true,masks:[]}));
 p.files[0].masks=[C.mask({x:.2,y:.2,w:.25,h:.25,color:'#000000',start:1,end:2}),C.mask({type:'模糊',x:.5,y:.1,w:.2,h:.2,start:0,end:4}),C.mask({type:'马赛克',x:.5,y:.6,w:.2,h:.2,start:0,end:4,strength:30})];
 const hashes=[hash(source),hash(portrait)],info=await engine.prepare(p);check('重新读取真实素材参数',info.plan.total===7&&info.width===320&&info.height===180&&info.fps===25);
 const preview=await engine.preview(p.files[0],1.5,p.files[0]);check('真实预览返回 PNG',preview.startsWith('data:image/png;base64,iVBOR'));await fs.promises.writeFile(path.join(dir,'真实处理预览.png'),Buffer.from(preview.split(',')[1],'base64'));
 for(const type of ['模糊','马赛克']){const file={...p.files[0],masks:[C.mask({type,x:0,y:0,w:1,h:1,strength:30,start:1,end:2})]},plain={...file,masks:[]};const before=await engine.preview(file,.5),reference=await engine.preview(plain,.5),active=await engine.preview(file,1.5),activeReference=await engine.preview(plain,1.5),after=await engine.preview(file,2.5),afterReference=await engine.preview(plain,2.5);check(type+' 预览按时间范围生效',before===reference&&active!==activeReference&&after===afterReference);}
 const proxy=path.join(dir,'播放兼容副本.mp4');await engine.playback(portrait,proxy);const proxyMeta=await engine.probe(proxy);check('兼容播放副本保留画面比例和时长',proxyMeta.codec==='h264'&&proxyMeta.width===180&&proxyMeta.height===320&&Math.abs(proxyMeta.duration-3)<.1);
 engine.encoder='h264_intentionally_unavailable';engine.start(p);const job=await wait();if(job.state!=='complete')throw Error(job.message);check('硬件失败真实回退软件编码',job.fallback&&job.encoder==='libx264');check('真实生成三个片段并保留尾段',job.outputs.length===3&&job.outputs[2].duration>.8&&job.outputs[2].duration<1.3);
 for(const output of job.outputs){const meta=await engine.probe(output.path);check('输出格式 '+output.name,meta.codec==='h264'&&meta.audioCodec==='aac'&&meta.width===320&&meta.height===180&&Math.abs(meta.fps-25)<.01);await engine.run('ffmpeg',['-v','error','-xerror','-i',output.path,'-map','0:v','-map','0:a','-f','null','-'],{timeout:30000});check('全片音视频可解码 '+output.name,true);}
 async function pixel(file,time,x,y){const b=await engine.run('ffmpeg',['-v','error','-ss',String(time),'-i',file,'-vf',`format=rgb24,crop=1:1:${x}:${y}`,'-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],{binary:true});return [...b];}
 const first=job.outputs[0].path,inside=await pixel(first,1.5,95,55),before=await pixel(first,.5,95,55),after=await pixel(first,2.5,95,55);check('纯色只在指定时间生效',Math.max(...inside)<15&&Math.max(...before)>30&&Math.max(...after)>30);
 const last=job.outputs[2].path,edge=await pixel(last,.3,10,90),center=await pixel(last,.3,160,90);check('混合比例补黑边且无音轨素材正常处理',Math.max(...edge)<15&&Math.min(...center)>220);
 await assert.rejects(()=>engine.prepare(p),/同名/);check('已有输出拒绝覆盖',true);check('源视频字节未改变',hash(source)===hashes[0]&&hash(portrait)===hashes[1]);
 const cancel=C.clone(p);cancel.settings.baseName='取消检查';engine.start(cancel);engine.cancel();const stopped=await wait();check('取消后不发布片段',stopped.state==='cancelled'&&!(await fs.promises.readdir(out)).some(n=>n.startsWith('取消检查')));
 const copy=C.clone(p);copy.settings.baseName='无损检查';copy.files=[{...copy.files[0],masks:[]}];const cp=await engine.prepare(copy);check('相同编码无效果走无损路径',cp.copy);engine.start(copy);const copied=await wait();if(copied.state!=='complete')throw Error(copied.message);check('无损路径生成可解码视频',copied.outputs.length===2);for(const f of copied.outputs)await engine.run('ffmpeg',['-v','error','-xerror','-i',f.path,'-f','null','-']);
 check('临时文件清理完成',!(await fs.promises.readdir(out)).some(n=>n.startsWith('.frameflow-')));
 const parsed=C.parse(JSON.stringify(info.project));check('项目持久化保留时间范围与全部素材',parsed.files.length===2&&parsed.files[0].masks[0].start===1&&parsed.files[0].masks[0].end===2);
 const separate=C.clone(p);separate.settings={...p.settings,baseName:'独立无损',concat:false,fit:'none'};separate.files.forEach(f=>f.masks=[]);
 const separatePlan=await engine.prepare(separate);check('关闭拼接适配允许混合尺寸独立无损分段',separatePlan.copy&&separatePlan.groups.length===2&&separatePlan.plan.segments.length===3);engine.start(separate);const independent=await wait();if(independent.state!=='complete')throw Error(independent.message);check('独立输出保留各自尺寸且不强加音轨',independent.outputs[0].width===320&&independent.outputs[2].width===180&&independent.outputs[2].height===320&&!independent.outputs[2].audioCodec&&independent.outputs.every(f=>f.mode==='copy'));
 const packets=async file=>JSON.parse(await engine.run('ffprobe',['-v','error','-select_streams','v:0','-show_packets','-show_data_hash','sha256','-show_entries','packet=data_hash','-of','json',file])).packets.map(p=>p.data_hash);
 check('直接复制视频压缩数据逐包一致',JSON.stringify(await packets(source))===JSON.stringify((await Promise.all(independent.outputs.slice(0,2).map(f=>packets(f.path)))).flat()));
 const joined=C.clone(separate);joined.settings.concat=true;joined.settings.baseName='冲突';await assert.rejects(()=>engine.prepare(joined),/开启画面适配/);check('关闭适配不会偷偷缩放混合尺寸',true);
 joined.settings.fit='letterbox';joined.settings.baseName='自动统一';const joinedPlan=await engine.prepare(joined);check('不兼容参数自动计划容错重编码并提示',!joinedPlan.copy&&joinedPlan.groups[0].recover&&joinedPlan.warnings.some(t=>t.includes('不兼容')));engine.start(joined);const joinedResult=await wait();if(joinedResult.state!=='complete')throw Error(joinedResult.message);check('不兼容素材确实重编码并统一尺寸',joinedResult.outputs.every(f=>f.mode==='encode'&&f.width===320&&f.height===180));
 const cleanJoin=C.clone(copy);cleanJoin.settings.baseName='兼容拼接';cleanJoin.files.push({...C.clone(cleanJoin.files[0]),id:C.id()});engine.start(cleanJoin);const cleanResult=await wait();if(cleanResult.state!=='complete')throw Error(cleanResult.message);check('兼容拼接没有触发重编码',cleanResult.outputs.every(f=>f.mode==='copy'));
 const frames=async file=>(await engine.run('ffmpeg',['-v','error','-i',file,'-map','0:v:0','-fps_mode','passthrough','-f','framemd5','-'])).split('\n').filter(line=>line&&!line.startsWith('#')).map(line=>line.split(',').pop().trim());
 // Remuxing may rewrite H.264 parameter-set headers; decoded frame hashes must still match exactly.
 const originalFrames=await frames(source);check('兼容拼接画面逐帧无损',JSON.stringify((await Promise.all(cleanResult.outputs.map(f=>frames(f.path)))).flat())===JSON.stringify([...originalFrames,...originalFrames]));
 const hevc=path.join(dir,'H265.mp4');await engine.run('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=160x90:rate=25:duration=2','-c:v','libx265','-preset','ultrafast','-x265-params','log-level=error','-tag:v','hvc1',hevc]);const hp=C.clone(separate);hp.settings.baseName='H265无损';hp.files=[{...hp.files[0],path:hevc,name:'H265.mp4',masks:[]}];engine.start(hp);const hevcResult=await wait();if(hevcResult.state!=='complete')throw Error(hevcResult.message);check('H265无打码保留编码而非强转H264',hevcResult.outputs[0].codec==='hevc'&&hevcResult.outputs[0].mode==='copy');
 const packetInfo=JSON.parse(await engine.run('ffprobe',['-v','error','-select_streams','v:0','-show_packets','-show_entries','packet=pos,size,pts_time,flags','-of','json',source])).packets.find(p=>Number(p.pts_time)>1.2&&!p.flags.includes('K'));
 const damaged=path.join(dir,'码流损坏.mp4'),data=fs.readFileSync(source);data.fill(0,Number(packetInfo.pos)+5,Number(packetInfo.pos)+Number(packetInfo.size));await fs.promises.writeFile(damaged,data);
 await assert.rejects(()=>engine.run('ffmpeg',['-v','error','-xerror','-err_detect','explode','-i',damaged,'-f','null','-']));check('损坏测试素材确实存在解码错误',true);
 const repair=C.clone(copy);repair.settings.baseName='自动修复';repair.files[0].path=damaged;repair.files[0].name='码流损坏.mp4';engine.start(repair);const repaired=await wait();if(repaired.state!=='complete')throw Error(repaired.message);check('真实码流异常自动切换容错重编码',repaired.fallback&&repaired.outputs.every(f=>f.mode==='encode')&&repaired.warnings.some(w=>w.includes('自动切换容错')));for(const f of repaired.outputs)await engine.run('ffmpeg',['-v','error','-xerror','-i',f.path,'-f','null','-']);
 const elapsed=repaired.elapsed;await new Promise(r=>setTimeout(r,1100));check('任务用时完成后冻结',elapsed>0&&engine.status().elapsed===elapsed);check('所有分支均清理临时文件',!(await fs.promises.readdir(out)).some(n=>n.startsWith('.frameflow-')));
 await fs.promises.writeFile(path.join(dir,'report.json'),JSON.stringify({health,checks,outputs:job.outputs,source,portrait},null,2));console.log('ALL PASS '+checks.length+' '+dir);
}
main().catch(e=>{console.error(e);process.exitCode=1;});
